{{- if .Values.nginx.enabled }}

# templates/nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-nginx
  labels:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-nginx
spec:
  type: ClusterIP
  selector:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

# templates/php-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.nginx.replicas | default 1 }}
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-nginx
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-nginx
      annotations:
        timestamp: {{ now | quote }}
    spec:
      containers:
      - name: {{ .Release.Name }}-nginx
        image: {{ .Values.nginx.image }}
        imagePullPolicy: {{ .Values.nginx.pullPolicy | default "IfNotPresent" }}
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      serviceAccount: {{ .Release.Name }}-srv-account
      serviceAccountName: {{ .Release.Name }}-srv-account
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-nginx-conf

{{- end }}