dockerRegistry:
  enabled: false
  host: ""
  loginid: ""
  password: ""

ingress:
  enabled: true
  appHost: "dootask.example.com"
  className: "nginx"
  annotations: 
  # tls:
  #   - secretName: tls-secret
  #     hosts:
  #       - dootask.example.com

nginx:
  enabled: true
  servicePort: 80
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: hub.hitosea.com/cossim/nginx
  pullPolicy: Always

php:
  enabled: true
  servicePort: 20000
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: hub.hitosea.com/cossim/php:swoole-8.0.rc15
  pullPolicy: Always
  mode: production
  lang: C.UTF-8

redis:
  enabled: true
  servicePort: 6379
  image: redis:alpine
  pullPolicy: IfNotPresent
  storageClass: standard
  volumeSize: 1Gi

mariadb:
  enabled: true
  servicePort: 3306
  image: mariadb:10.7.3
  pullPolicy: IfNotPresent
  storageClass: standard
  volumeSize: 10Gi

office:
  enabled: true
  servicePort: 80
  image: onlyoffice/documentserver:7.5.1.1
  pullPolicy: IfNotPresent
  storageClass: standard
  volume:
    logsSize: 1Gi
    dataSize: 10Gi

fileview:
  enabled: true
  servicePort: 8012
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: kuaifan/fileview:4.2.0-SNAPSHOT-RC25
  pullPolicy: IfNotPresent
  env:
    KK_CONTEXT_PATH: /fileview
    KK_OFFICE_PREVIEW_SWITCH_DISABLED: true
    KK_FILE_UPLOAD_ENABLED: true
    KK_MEDIA: "mp3,wav,mp4,mov,avi,wmv"

drawioWebapp:
  enabled: true
  servicePort: 8080
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: jgraph/drawio:20.8.20
  pullPolicy: IfNotPresent

drawioExport:
  enabled: true
  servicePort: 8080
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: kuaifan/export-server:0.0.1
  pullPolicy: IfNotPresent

minder:
  enabled: true
  servicePort: 80
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: kuaifan/minder:0.1.3
  pullPolicy: IfNotPresent

approve:
  timeZone: PRC
  enabled: true
  servicePort: 80
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: kuaifan/dooapprove:0.0.11
  pullPolicy: IfNotPresent

ai:
  enabled: true
  servicePort: 8881
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: kuaifan/dooai:0.2.0
  pullPolicy: IfNotPresent

okr:
  enabled: true
  servicePort: 5566
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  image: kuaifan/doookr:0.4.3
  pullPolicy: IfNotPresent

env:
  app:
    name: DooTask
    env: local
    key: base64:MF5T+3xkrFnIoBv3lGDCOWvgW50wVZqZ83UcpMPW/YY=
    debug: false
    scheme: auto
    url: http://localhost
    id: ""
    ippr: ""
    port: 2222
    sslPort: ""
    devPort: ""
    timezone: PRC

  log:
    channel: stack
    level: debug

  database:
    connection: mysql
    host: ""
    port: 3306
    name: dootask
    user: dootask
    password: 123456
    rootPassword: rootpassword
    prefix: pre_

  broadcastDriver: "log"

  cache:
    driver: redis

  queue:
    connection: redis

  session:
    driver: redis
    lifetime: 120

  memcached:
    host: 127.0.0.1

  redis:
    host: ""
    password: null
    port: 6379

  mail:
    mailer: smtp
    host: mailhog
    port: 1025
    username: null
    password: null
    encryption: null
    fromAddress: null
    fromName: "${APP_NAME}"

  aws:
    accessKeyId: ""
    secretAccessKey: ""
    defaultRegion: us-east-1
    bucket: ""

  pusher:
    appId: ""
    appKey: ""
    appSecret: ""
    appCluster: mt1

  laravels:
    listenIp: 0.0.0.0
    listenPort: 20000